### ISSUE TITLE
before_action: require_admin does not work for apps not using devise

### ISSUE THREAD

**Issue by pavankat** [ankane/blazer#186]
literally have this line in blazer.yml:
```
before_action: require_admin
```

and this in application_controller.rb.

```
def require_admin
  # depending on your auth, maybe something like...
  current_user && current_user.admin?
end
```

and it lets unauthenticated users get to localhost:3000/blazer

**Comment by ankane** [comment]
Hey @pavankat, I've used `before_admin` successfully with Devise. I think it's an issue specific to your app. If you find stronger evidence it's a Blazer bug, please open another issue with more details.

**Comment by jungbunzlav** [comment]
@ankane I have the same issue here. 

I am **NOT** using Devise and any outcome of the method stated under 'before_action' lets unauthenticated users get to blazer.

You are writing "I've used before_admin successfully **with** Devise.". - Did you ever used it **without** Devise?

**Comment by ankane** [comment]
Hey @jungbunzlav, there's nothing specific to Devise in Blazer. Make sure your `before_action` method has the correct return value.

**Comment by jungbunzlav** [comment]
@ankane and that would be which value? I tried to return a simple `true` or `false` and with both return values the blazer stats where still accessible.

**Comment by ankane** [comment]
Sorry @jungbunzlav, but I won't be able to help debug app-specific issues. My last piece of advice would be to make sure you uncomment the `before_action` line in the config and restart your web server, and make sure you don't have a method with the same name in your controller that's overriding it.

**Comment by jungbunzlav** [comment]
@ankane I am not asking for debugging my app. Just asking to acknowledge that there my be a bug with blazer version 1.8.2 and without using devise.

I renamed the method to `require_admin_foo_bar` - which is a pretty unique name. Still the `before_action` gets called (I ensured it with some debug output) and still has not impact on showing the blazer page. 

As far a I read the blazer code and my own app a return value of `true` or `false` or `foo` has no impact on any authentication... The `before_action` should implement something like `redirect_to root_path unless current_user&.admin?` (which gives me a "too many redirects" error btw) because blaze is just calling the `before_action` but does not check the returned values:

```
  if Blazer.before_action
    before_action Blazer.before_action.to_sym
  end
```

Or am I totally wrong?

**Comment by jungbunzlav** [comment]
Well I helped myself with something like this:

```
  def require_admim
    unless current_user&.admin?
      raise_not_found
    end
  end
``` 

Which is quite crude and differs from the gem's documentation...

**Comment by ankane** [comment]
Yes, you'll need to render or redirect, just like you would with any authorization `before_action`. Sorry if that wasn't clear before.

**Comment by ankane** [comment]
Fixed the docs. Sorry about that.
