### ISSUE TITLE
Idea, Mongoid Support

### ISSUE THREAD

**Issue by waheedi** [ankane/blazer#228]
Hi Andrew,

Such great progress and great gems. I really value your time and effort in making these open source projects, as I understand how important time is.

I thought it would be a good idea to add integration to mongoid, I'm not sure if thats already implemented or if there is PR for it.

I would be happy to implement it if you gave me some guidelines and hints.

All my best,

Waheed

**Comment by ankane** [comment]
Hey @waheedi, thanks for the suggestion. It'll be extra work to support Mongoid over the long run, so it's not something I'd like to add right now. Since it's open source, you're welcome to create your own fork that supports it. You'll need to change the model classes and likely many of the database calls in the controllers (both are in the `app` directory).

**Comment by phstc** [comment]
@ankane just double-checking. Blazer requires ActiveRecord, right?

I'm using Mongoid, and I was trying to use the Mongo adapter, but I'm getting `uninitialized constant Blazer::ActiveRecord`, checking the code it seems `ActiveRecord` is a requirement.

**Comment by ankane** [comment]
Yeah, Active Record is a requirement.
