### ISSUE TITLE
Not getting pie charts or bar charts

### ISSUE THREAD

**Issue by DhanashreeDorage** [ankane/blazer#240]
Hello,

I am trying to get pie chart or bar chart with below queries but I am getting line chart for all.

SELECT date_trunc('day', created_at), COUNT(*) AS pie FROM uploads GROUP BY 1

SELECT user_id, COUNT(*) AS bar FROM "file_logs" GROUP BY 1

![blazer](https://user-images.githubusercontent.com/12697581/55585807-7fa4e500-56f5-11e9-9271-b76770236c9e.PNG)

**Comment by guaguasi** [comment]
@DhanashreeDorage You've probably figured this out already, but the reason is because the types of values and their orders.

For a pie chart, the first value must be a string and in your query it's a timestamp/date for a Line chart: `2+ columns - timestamp, numeric(s)`
For a bar chart, the first value must be a string and your query it's numeric. Two numeric values is a Scatter chart: `2 columns - both numeric`

Hope this helps anyone else that may come along, too.

**Comment by ankane** [comment]
Thanks @guaguasi 👍

**Comment by njcameron** [comment]
This might help future googlers:

`SELECT date_trunc('week', time)::date AS week `

to

`SELECT to_char(date_trunc('week', time), 'DD/MM/YYYY') AS week`
