### ISSUE TITLE
Feature request - webpacker

### ISSUE THREAD

**Issue by alec-c4** [ankane/blazer#243]
Hi,
Do you have plans to add webpacker support? It would be useful because of webpacker becomes the main tool for managing assets for rails applications.

**Comment by ankane** [comment]
Hey @alec-c4, Rails 6 still includes Sprockets, so it's not needed right now. Blazer assets are completely separate from application assets, so this shouldn't make a difference.

**Comment by dzirtusss** [comment]
Just FYI, this is how it is done in ActiveAdmin https://github.com/activeadmin/activeadmin/pull/5855

**Comment by jmoore53** [comment]
I was going to comment on this with a question and ask about possible workarounds because I ran into a similar issue, but ended up just adding sprockets & uglifier to my Gemfile, and then setting `config.assets.compile=true` in `config/environments/production.rb`

It's a sloppy and noticeably slow workaround to compile assets on the fly in production, but it works for my small production environment because all other assets end up getting compiled via webpacker for the users/public pages and this is behind and admin login/ authn/z. 

I'm aware this issue is marked closed, but I wanted to share it out here in case anyone was looking for a workaround.
