### ISSUE TITLE
Blazer Async Integration with Database

### ISSUE THREAD

**Issue by coliveiraluca** [ankane/blazer#271]
Hello,

So we have some queries that are way too big and heavy for browser rendering, there is any chance that the result of the query on the view can crash the web browser in that process? And what would it be your suggestion to surpass that problem.

We had an idea to avoid any problem like that, that was creating an async process that would go to sidekiq and eventually send the generated csv to the user's email. The problem is that we tried to replicate the process of just running a query on the Rails Console and we were not able to do so.

Here are the step that we followed:

`require 'securerandom'`
`run_id = SecureRandom.uuid`
`query = Blazer::Query.last`
`data_source = Blazer.data_sources[query.data_source]`
`result = data_source.run_results(run_id)`

We had a few queries saved, so we used one of them. Also, just to make sure nothing was out of place we executed the rails server and executed the queries through the interface and worked just fine.   

Regards,

**Comment by ankane** [comment]
Hey @coliveiraluca, if a result set is really large, it can cause performance issues in the browser. I think the ideal way would be to only render visible rows in the DOM, but I'm not sure this is a large enough problem to warrant a bigger change like that (would need to change the query results endpoint to return JSON instead of HTML and then do all the rendering client-side).

If you find any easy performance wins, feel free to submit a PR.

**Comment by ankane** [comment]
Cleaning up issues
