### ISSUE TITLE
How to modify Blazer views ?

### ISSUE THREAD

**Issue by DhanashreeDorage** [ankane/blazer#329]
Hello,

I am trying to modify Blazer views. How can I add and access all blazer views?

Before creating an issue, please check out the Contributing Guide:

https://github.com/ankane/blazer/blob/master/CONTRIBUTING.md

Thanks!

**Comment by ankane** [comment]
Hey @DhanashreeDorage, you'll probably want to fork the gem to modify the views. Check out #50 for previous discussion.

**Comment by brandondrew** [comment]
@DhanashreeDorage what if you forked Blazer to look for views in an app's `app/views/blazer` directory?  It could use anything it found there instead of the defaults that ship with it.  

(It would also be nice to be able to embed the Blazer UI in your application's UI, but that might be a separate effort.  🤔)
