### ISSUE TITLE
[Idea] improve map performance

### ISSUE THREAD

**Issue by lrgalego** [ankane/blazer#336]
Right now blazer uses mapboxjs library to render pins for all rows with lat and on.
This works great and it's one of the features I love about blazer.
Sadly when the query result has some thousands of entries the map gets really slow to a point it's useless.
If we change the library that renders the pins we can render hundreds of thousands of pins without this issue.

We can use libraries like [mapboxgl-js](https://docs.mapbox.com/mapbox-gl-js/api/) or [deck.js](https://deck.gl/) for the pin layer.

I can work on it but would appreciate some guidance on where to start.

**Comment by ankane** [comment]
Hey @lrgalego, Mapbox GL makes sense to me. Since there's different pricing, it's probably a good idea to wait until the next major version of Blazer to make the switch (not sure when that'll be yet, so you'll probably want to run your own fork). If you search the code for `blazer_maps?`, it should bring up the relevant code.
