### ISSUE TITLE
Has undeclared runtime dependencies

### ISSUE THREAD

**Issue by bf4** [ankane/blazer#345]
Steps to reproduce

1. Install gem
2. Run migrations
3. `bin/rails zeitwerk:check` raises `NameError: uninitialized constant Blazer::ActionMailer`

Investigation:

Gemspec depends on railties (not rails meta-gem, yay!) but 
https://github.com/ankane/blazer/blob/a505849e893abef50c4128c2b3bfc9fae5ad2c86/app/mailers/blazer/check_mailer.rb (and the [slack notifier](https://github.com/ankane/blazer/blob/a505849e893abef50c4128c2b3bfc9fae5ad2c86/app/mailers/blazer/slack_notifier.rb) ) depend on ActionMailer

Proposal

1. Add gemspec dependency on `activerecord`, `activejob`, `actioncontroller`, `actionmailer` (and perhaps others. I didn't look too closely)
2. Consider making the actionmailer and activejob dependencies optional.

I'm up for making a PR

**Comment by ankane** [comment]
Hey @bf4, thanks for bringing this up. `railties` already includes `actioncontroller` and `activejob` is already optional (only included when `async: true`), so I think `actionmailer` is the only issue. Instead of including it in `app`, I've moved it to `lib` with `autoload`, so it should only be included when needed and `rails zeitwerk:check` now passes. Let me know if you still run into issues.

**Comment by bf4** [comment]
Awesome.  I'll try it out.

**Comment by bf4** [comment]
Confirmed working as advertised.  Booting Rails works.  Explicitly referencing `Blazer::CheckMailer` raises

```
NameError: uninitialized constant Blazer::ActionMailer
Did you mean?  ActionView
from .bundle/vendor/ruby/2.7.0/gems/blazer-2.4.7/lib/blazer/check_mailer.rb:2:in `<module:Blazer>'
```

Awesome
