### ISSUE TITLE
ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken)

### ISSUE THREAD

**Issue by duboff** [ankane/blazer#35]
For API only app, I get the error above. The culprit is this:

``` rb
protect_from_forgery with: :exception
```

In https://github.com/ankane/blazer/blob/master/app/controllers/blazer/base_controller.rb#L6

Why is blazer overwriting the default protect_from_forgery  from the ApplicationController. Doesn't seem like it should be the case. I reopened and removed the line and everything is working. Happy to submit a PR if this makes sense.

PS absolutely love Blazer, saves us a lot of headache.

**Comment by ankane** [comment]
It probably makes sense to keep the application default, in which case you'd want to exclude `verify_authenticity_token` from the `skip_filter` list.

**Comment by gen0cide-** [comment]
@ankane - Any hesitation accepting this PR? Would rather not be using a fork :)

**Comment by ankane** [comment]
Yeah, my previous comment was never addressed.  Thinking about it again, I'm not sure it makes sense.  What CSRF protection method would you use instead?

**Comment by duboff** [comment]
@ankane I am sorry for not following up on this but I did not quite understand what you meant in the previous comment. Would be very keen to reopen discussions. I would think Blazer should just respect the application default.

@gen0cide you don't necessarily need a fork. We just have a Blazer::BaseController with:
```
protect_from_forgery with: :null_session
```

**Comment by ankane** [comment]
Hey @duboff, no worries. How are you doing authentication?

**Comment by duboff** [comment]
We use Clearance gem for the admin pages which Blazer is a part of.

**Comment by ankane** [comment]
I'll follow up over email since this involves security.

**Comment by richardvenneman** [comment]
@duboff did you manage to get this to work? I tried everything from monkey patching to forking and removing the `protect_from_forgery` directive as well as inheriting from `ActionController::Base`. I always ended up with the following error:

> {"status":500,"error":"Internal Server Error","exception":"#\u003cActionView::Template::Error: undefined local variable or method `new_query_path' for #\u003c#\u003cClass:0x007fb3f86eb2d0\u003e:0x007fb3f6e95a00\u003e\u003e","traces":{"Application Trace":[{"id":88,"trace":"appsignal (2.1.0) lib/appsignal/rack/rails_instrumentation.rb:16:in `call'"}]

Really hope someone has gotten Blazer to work with rails-api!

**Comment by duboff** [comment]
We do have it working, however, @ankane has personally emailed me saying our solution is not great security-wise. I don't have any other one though. My solution is to have a controller `app/controllers/blazer/base_controller.rb` with the following:
`protect_from_forgery with: :null_session`

The only other solution is to switch off `api_only` mode I believe.

**Comment by richardvenneman** [comment]
@duboff Thanks for your fast reply, good to hear that you have it working.

I am using with Blazer 1.7.9 and added the controller override in `/app/controllers/blazer/base_controller.rb`.

Even when using `null_session` the controller depends on `ActionController::RequestForgeryProtection`. Since this module is not included in the `ActionController::API` base class the following error is thrown:

> ActionController::RoutingError: undefined method `protect_from_forgery`

.. so I included `ActionController::RequestForgeryProtection` in the `Blazer::BaseController`. Which yields:

> ActionController::RoutingError: undefined method `layout' 

At this point I believe the only option is to have the `Blazer::BaseController` inherit from  `ActionController::Base` instead of `ApplicationController` which has `ActionController::API` as super. But this yields the following error again:

> ActionView::Template::Error: undefined local variable or method `new_query_path'

Currently I don't think turning of `api_only` is a solution. Maybe it should be possible to specify the engine's parent_controller like [Devise](https://github.com/plataformatec/devise/blob/master/lib/devise.rb#L227) or [rails_admin](https://github.com/sferik/rails_admin/blob/master/lib/rails_admin/config.rb#L62)? But in this case, the `protect_from_forgery` line should be removed anyways.

**Comment by duboff** [comment]
Hmm, it's definitely working for us.

Probably a better solution is to separate blazer into a whole new app?

**Comment by richardvenneman** [comment]
Great suggestion, why didn't I think of that 🤔

**Comment by ankane** [comment]
Cleaning up issues
