### ISSUE TITLE
[idea] add Frontend Bundlers

### ISSUE THREAD

**Issue by rikoroku** [ankane/blazer#422]
I've been using this gem with Propshaft gem and got an error `upstream sent too big header while reading response header from upstream` on Nginx.
I guess that this is due to [this](https://github.com/ankane/blazer/commit/e4b402c5698567d06ce744bb814fe5266dd846da) which adds multiple references if `Propshaft::Railtie` defined.

As noted in the [issue](https://github.com/ankane/blazer/issues/379), we may have to adopt bundler tools like [jsbuilding-rails](https://github.com/rails/jsbundling-rails) and [cssbuilding-rails](https://github.com/rails/cssbundling-rails)

**Comment by ankane** [comment]
Hey @rikoroku, which files get that error?

**Comment by ankane** [comment]
It looks like the largest asset file is under 1MB, which nginx should have no problem serving, so seems like something else may be going on.

**Comment by stevenbarragan** [comment]
I'm using Propshaft and I'm having the same issue. I can see in the logs the rails app returns a 200 on the `/blazer` route but then nginx throws a `502 Bad Gateway`, nginx logs only say:
```
*3436865 upstream sent too big header while reading response header from upstream
```
I'm not able to see anything from the response.

**Comment by ankane** [comment]
Ah, didn't understand the issue earlier. It looks like Rails expects proxies to be able to handle up to [8,000 bytes](https://github.com/rails/rails/pull/42056). The value is currently hardcoded, but it'd be good to submit a PR to Action View to make it configurable for those who need this (since it can affect more than just Blazer). Another option for users is to [disable the `Link` header](https://github.com/rails/rails/pull/39939#issuecomment-786549537):

```ruby
config.action_view.preload_links_header = false
```
