### ISSUE TITLE
Easier overriding of Blazer templates

### ISSUE THREAD

**Issue by jonahgeorge** [ankane/blazer#50]
@ankane 

What are your thoughts on extracting the various navs ([Dashboards#show](https://github.com/ankane/blazer/blob/82d1a70c3ab911c797038660d22c46b5618598ba/app/views/blazer/dashboards/show.html.erb#L17-L31) and [Queries#show](https://github.com/ankane/blazer/blob/82d1a70c3ab911c797038660d22c46b5618598ba/app/views/blazer/queries/show.html.erb#L17-L36)) into partials so that they can be more easily overridden by a parent application. This is something that I've been wanting to be able to do and it appears that others do as well (#49). 

Currently if we override the layout in `Blazer::BaseController`, these navs still sit on top of whatever navigation was introduced by the parent application's layout file.

**Comment by ankane** [comment]
@jonahgeorge open to the idea. curious to see how this would look.

**Comment by cycomachead** [comment]
I send this. Similar to #49, I'd really like to just embed my app's navbar at the top. (I don't really care if things aren't particularly pretty for a case like this -- just functional. (The pretty can come later, I suppose.)

**Comment by cycomachead** [comment]
So, I just tried something:

I just copied `blazer/application.html.erb` in `layouts/` to my app's layouts folder - and things are pretty easy to override. The challenge is, since Blazer is mounted as a gem the routes in my navbar partial all need to be `main_app.route_fn` now, which is a bit of a drag, but not terrible. I imagine with a more complex app than I currently have, that more things could break.

I think gems (like devise) usually support overriding by just having a generator "install" that copies the views to the right places, and a bit of documentation.

**Comment by onlyyouandty** [comment]
Hi, I just figured that blazer is overriding devise gem in my app. Everything works fine in development but in production here is the error when I clicked on the login button `undefined method `session_path'` and when I click on the signup button, I get `undefined method `registration_path'` error. How do I fix this, please?

**Comment by ankane** [comment]
Hey @onlyyouandty, this doesn't seem related to the idea discussed here. Please file a new issue with more info about why you think Blazer is responsible.

**Comment by onlyyouandty** [comment]
Okay @ankane. :+1:

**Comment by diegomonteiro** [comment]
Should consider implementing the routes so that integrates with the defined inflectors because when I start my application Blazer does not render pages as it is creating wrong links.

Error:

![screenshot - 03-08-2016 - 10 10 30](https://cloud.githubusercontent.com/assets/5667573/17367113/013f1054-5965-11e6-8e0a-1c509fd934b7.png)

**Comment by ankane** [comment]
Hey @diegomonteiro, can you please file a new issue with more details?  This ticket is a feature request for customization.

**Comment by seanfcarroll** [comment]
+1

**Comment by seanfcarroll** [comment]
This is really a problem with Rails engines in general: how to mount an engine but make it appear to be a real part of the app rather then a bolt-on. The Devise solution seems to work well: you can easily override the views and mailers, and have access to the routes. It is also easy to selectively override controller actions.

I have Blazer mounted in my app, using my (Bootstrap) navbar. It's not a great solution and pretty hacky but maybe it will help someone. **Better solutions are welcomed**

1. Copy <pre>blazer/app/views/layouts/blazer/application.html.erb</pre> to <pre>app/views/layouts/blazer/application.html.erb</pre>

2. Add in the links to the parent styles and js

3. Add in the navbar

4. Hardcode the routes on the navbar, as I can't access the parent's routes. ie: 

```
          <li><%= link_to 'Graders', '/graders' %></li>
          <li><%= link_to 'Submissions', '/submissions' %></li>
          <li><%= link_to 'Results', '/results' %></li>
          <li><%= link_to 'Change Password', '/users/edit' %></li>
          <li><%= link_to 'Sign out', '/users/sign_out', :method => :delete %></li>
```

Instead of
```
          <li><%= link_to 'Graders', graders_path %></li>
          <li><%= link_to 'Submissions', submissions_path %></li>
          <li><%= link_to 'Results', results_path %></li>
          <li><%= link_to 'Change Password', edit_user_registration_path %></li>
          <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
```

**modified blazer/app/views/layouts/blazer/application.html.erb**
```
<!DOCTYPE html>
<html>
  <head>
    <title><%= blazer_title ? blazer_title : "Blazer" %></title>

    <meta charset="utf-8" />

    <%= stylesheet_link_tag "blazer/application" %>
    <%= javascript_include_tag "blazer/application" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script>
      <%= blazer_js_var "rootPath", root_path %>
    </script>
    <% if blazer_maps? %>
      <%= stylesheet_link_tag "https://api.mapbox.com/mapbox.js/v2.4.0/mapbox.css" %>
      <%= javascript_include_tag "https://api.mapbox.com/mapbox.js/v2.4.0/mapbox.js" %>
    <% end %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="container">
      <%= render 'layouts/navbar' %>
      <%= render partial: "layouts/flash_messages", flash: flash %>

      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>
```

**Comment by MadBomber** [comment]
What would work best for my apps is to provide blazer with the container ID from my app's layout into which I'd like to see the entire blazer content inserted.  That way I get by branding in header, footer and sidebars.

**Comment by ankane** [comment]
Thinking on this more,  an interface is not really something I want to think about / maintain. You can follow @seanfcarroll’s approach if you want to hack it.
